[package]
name = "delicate-scheduler"
version = "0.1.0"
authors = ["BinChengZhao <binchengZhao@outlook.com>"]
readme = "README.md"
edition = "2018"
build = "build/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.16.5"
delay_timer = "0.3.0"
actix-web = "3.3.2"
diesel = { version = "1.4.6", features = ["postgres", "mysql", "extras"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"

[build-dependencies]
autocfg = "1"
dotenv = "0.15.0"