language: node_js
node_js:
  - node
script:
  - npm run build
before_install:
  - yarn global add now
after_script:
  - |
    if [[ $TRAVIS_BRANCH == 'master' ]]; then
      echo $PROD_SITE_NOW_CONFIG >> dist/vercel.json && echo $PROD_DOC_NOW_CONFIG >> docs/vercel.json;
    else
      echo $DEV_SITE_NOW_CONFIG >> dist/vercel.json && echo $DEV_DOC_NOW_CONFIG >> docs/vercel.json;
    fi
  - cd ./dist
  - now -A vercel.json -t $NOW_TOKEN --prod -c
  - cd ../docs
  - now -A vercel.json -t $NOW_TOKEN --prod -c
