[package]
name = "delicate-executor"
version = "0.1.0"
authors = ["BinChengZhao <binchengZhao@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "^0.16.5"
delay_timer = {version = "^0.5.0", features = ["full"]}
actix-web = "^3.3.2"
futures = "^0.3"
env_logger = "^0.8"
serde = { version = "^1.0", features = ["derive"] }
serde_json = "^1.0.62"
json = "^0.12.4"
anyhow = "^1.0.38"
rsa = "^0.4.0"
rand = "^0.8.3"
async-lock = "^2.3.0"